# Intervalle de régénération en jours
interval-days: 7

# Nom du monde à régénérer
world: world

# Nombre de chunks de sécurité autour des claims
buffer-chunks: 2

# Avertissements avant régénération (en minutes)
warnings:
  - 30
  - 10
  - 5
  - 1
